### ISSUE TITLE
Bags are covering Sidbars

### ISSUE THREAD

**Issue by Cymjf** [Karl-HeinzSchneider/WoW-DragonflightUI#128]
I am playing SoD.
Normally when you have Bar 4 and/or Bar 5 enabled, bags are moving inwards to not cover the bars. With the latest update this does not work.

**Comment by Karl-HeinzSchneider** [comment]
Yes, the bag opening logic is completely overriden (since a long time ago). As default this is better, because some people (e.g. like my default) dont have the bars on the right side of the screen, so it doesn't really make sense to have this gap.
But I guess I can make it a setting. Will work on it for the next update.

**Comment by Karl-HeinzSchneider** [comment]
Added for the next version with f39a40cc02ea0efc2c63ae7b5d9394c9b7b3ef03 :

![image](https://github.com/user-attachments/assets/13c1a223-fa24-4dc1-8719-fc3879f12c1c)

**Comment by Cymjf** [comment]
Many thanks for your quick reply and fast rework.
Such a great addon.
Thank you very much.

Karl-HeinzSchneider ***@***.***> schrieb am Fr. 12. Juli 2024
um 00:15:
