### ISSUE TITLE
Character pane is broken with popular addon CharacterStatsClassic

### ISSUE THREAD

**Issue by sandervspl** [Karl-HeinzSchneider/WoW-DragonflightUI#132]
![image](https://github.com/user-attachments/assets/2cf458ce-675a-467e-8e87-1b5f5d7456c6)

https://www.curseforge.com/wow/addons/characterstatsclassic

It's a very popular addon, used by many people playing classic. Is it possible to get this fixed on your side or is this not possible?

**Comment by Karl-HeinzSchneider** [comment]
Hey!
I made a quick fix with 7e9c1347cc889645b3745e49810dba185bdd1ec3 : 
![image](https://github.com/user-attachments/assets/8c805ba8-88ba-450c-b6a9-fecf563e98a4)

**Comment by Karl-HeinzSchneider** [comment]
But you're using some other addon that changes the CharacterFrame, right? I see Gearscore, but also the rotate button is different, and theres a button left of the upper trinket slot.

**Comment by Karl-HeinzSchneider** [comment]
TacoTip compatibility: 3a728a072fc55598df23b972060663dbb1fdf240

**Comment by Karl-HeinzSchneider** [comment]
I'm using leatrix plus myself, but not every option is useful, and nearly every default option works fine. 
It's not possible to make everything compatible,  because LTP is destrucftive, and doesn't really care about other addons (except for sometimes ElvUI).
The old frames (Character, Talents, Spellbook etc) are 20 years old and not coded in a consistent style (and coded like shit tbh), and it's not possible to alter them without drawing custom textures for every frame, so I had to override the positions etc to match the modern style.

**Comment by Karl-HeinzSchneider** [comment]
You're using the 'Enhance Dressup' from LeatrixPlus, but also some other addon, because this doesn't add the arrow button left of your trinket1 slot.

**Comment by sandervspl** [comment]
Yes, correct, it's the enhanced dressup option. No worries if compat becomes too difficult. I'll disable it for now! Thanks for all the other compat work. Appreciate it

**Comment by Karl-HeinzSchneider** [comment]
New version is on its way to curseforge. Please let me know if you encounter (Era specific?) errors, or have any other ideas for improvements!
I'm working on getting every old Era frame into the modern Dragonflight style; Cata is more or less done with that.
