### ISSUE TITLE
Game freezes

### ISSUE THREAD

**Issue by bovanova1** [Karl-HeinzSchneider/WoW-DragonflightUI#142]
Hello i have a issue with the addon where my game freezes whenever i open dialogues. Like uh if i want to complete a quest it usualy freezs for up to 10 secs.
I dont know how to go on with it. Appreciate the help

**Comment by Karl-HeinzSchneider** [comment]
Hey,
have you tried to deactivated every other addon? I'm changing the dialogue/gossip frames, but its a one time change, so it should not affect anything. 
Are you getting any lua errors?
You could also try to deactivate the UI module.

**Comment by bovanova1** [comment]
so you want me to disable all other mods in favour of yours ? 
Im not sure how and why it happens but whenever i use this mod with any others the game just freezes

**Comment by Karl-HeinzSchneider** [comment]
I can't debug this if I don't know what you're using, or if its even "my fault".
DragonflightUI has ~15-25k users, and so far you're the only one reporting this, so I guess its more likely its something else. 

Try to disable the UI module first, then you know its some other addon because this module is the only one touching the dialogue frames.
