### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by IvikN** [Karl-HeinzSchneider/WoW-DragonflightUI#162]
Classic SoD
![image](https://github.com/user-attachments/assets/952fbf27-0617-4e99-a9be-f3944cd2fa73)
Profession window looks bugged. No icons, background is empty and have no frame. Would love to have naming of the created items be colored as it is in classic window, because arrows aren't enough for me personally to see with a glimpse. 
Love to be able to sort with materials available (classic doesn't have this for some reason).

![image](https://github.com/user-attachments/assets/621c2adf-9727-4b45-9654-357a3215f6b0)
Character window comes a bit out of the screen side, and this makes other addons that are linked to character window look a bit weird. by placing them under the character window. Would be great if you move character window back to the side of the screen without gap.

Otherwise, it's much appreciated addon. much cleaner and tidier than classic one. thanks for the developing it.

**Comment by Karl-HeinzSchneider** [comment]
Hey!

1) Crafting:
I think you got some lua errors that would help. You're using auctionator ist seems, but that has compatibility that should work: 
![image](https://github.com/user-attachments/assets/321d3c91-3f6e-4992-824e-29e0eff77fe1)
So I would say its something different. 
But the leatherworking background isn't shown, so I would guess theres an error somewhere.
Using Bugsack + Buggrabber would be best to see those.

Yeah the arrows are a bit different than oldschool default, but not sure how colored text would fit the style; I'll investigate and maybe add a custom option for that.

You should have a filter for skill up or having alle the materials: 
![image](https://github.com/user-attachments/assets/351a3465-6d5a-421d-80cb-62b8427b6518)
Also you can use the searchbox, it trys to match the name of the crafted item, and every material it uses.

2) Characterframe:
The default character frame has hardcoded borders etc, and not in a good way. I changed that to match the newer frames, and blizzard did that too with newer stuff, only a few of the really old frames are that way: 
![image](https://github.com/user-attachments/assets/7ec5622b-16e5-4d4d-a2e4-ad99526d16c8)
![image](https://github.com/user-attachments/assets/c52f0126-0088-43a9-8591-74a84b298c9b)
A lot of other addons place their own stuff in a hardcoded, bad way, like say '42 pixels above the bottom', and the bottom of the frame is like 30pixel of emptiness. Insted they could set them relative to more specific stuff, like 5px left of the 3D model. 

That feels like a hacked together way, (like a lot of blizzard code lol), but it doesn't really make sense to hack my own stuff onto it with  *a lot* of work, because for example the cataclysm frames are made in the newer way.

I guess the other addons probably wont update their code becasue it means work, but if somebody reports something like that, I can make a compatibility patch, and move the buttons/frames etc to the right position.
Sometimes thats simple , sometimes it requires more work. I'll do it if its some addon more people are using, or if its somebody requesting that I know/has donated for example.

**Comment by Karl-HeinzSchneider** [comment]
The next version will have an option to disable changing the Characterframe: 1e2565954753b7011c0c723aa0f0864de38990f1
Could be useful for you. But if you want, I can still add compatibility if you have some specific addon you are using.
