### ISSUE TITLE
[BUG] Classic Era: Micromenu position changes on fadeout due to unintended addon interaction

### ISSUE THREAD

**Issue by AbsoluteTerror** [Karl-HeinzSchneider/WoW-DragonflightUI#182]
This appears to be an undesired interaction with another addon (DialogueUI) but only on Classic Era. Other addons with similar behavior not yet tested. The new position of the micromenu appears to have the same offset as it does with DragonflightUI in Cataclysm Classic, as the character info button is in a similar position. 

Steps to reproduce:

1. With both DragonflightUI and DialogueUI installed enter the world or /reload.
2. Set DialogueUI to fade out UI on NPC interaction (on by default).
3. Interact with any friendly NPC with a gossip window (i.e. quest giver, innkeeper).
4. The micromenu has now shifted position to the left.

Addons installed:
 - [DialogueUI v0.3.6b](https://github.com/Peterodox/YUI-Dialogue/releases/tag/v0.3.6-b) (current)
 - DragonflightUI v0.14 (or earlier)

**Comment by Karl-HeinzSchneider** [comment]
Hey,
thanks for the great report!

I think the issue is some default blizzard code, and related to something two or three others reported, but I could never reproduce: the micromenu position gets repositioned after hiding the UI, so when pressing the default alt + Y(Z), its the same thing.  Somehow this only happens on Era. I'll dig into the blizzard code!

**Comment by Karl-HeinzSchneider** [comment]
Ha, that was easy:
It was kind of already fixed, because I was already hooking the MoveMicro function, which gets called when the UI is shown again, and this triggers for example when you exit a vehicle. The only problem was, this was only hooked on Cata, because I didn't know this bug would also happen after normally hiding the UI.

If you want the fix now, you can check out the alpha version on curseforge, which should be online in ~15min.
