### ISSUE TITLE
[BUG] Some Frames Won't Change in Chinese Wotlk Classic Client.

### ISSUE THREAD

**Issue by ahe-meow** [Karl-HeinzSchneider/WoW-DragonflightUI#237]
**Describe the bug**
Some frames won't change in Chinese Wotlk Classic client.

What's working:
1.Minimap
2.All Bars
3.Unit Frames
4.Bags
5.Micromenu
6.Quest Log

What's not work:
1.Character Frame (and any of its tabs)
2.Friend List Frame (and any of its tabs)
3.Spell Book Frame
4.Talent Frame (and any of its tabs)
5.Profession Frame
6.Trainer Frame

**Error Log**
There is no such logs relate to this isssue. Bug Sucker/Grabber caught no error.

**Versions (please complete the following information):**
 - WoW: Wrath classic (chinese)
 - Addon v0.15.2

**Additional context**
![1724304165978](https://github.com/user-attachments/assets/6691547e-0fd4-41e9-83af-836688cd02f7)

**Comment by Karl-HeinzSchneider** [comment]
Hey,
thanks for the detailed issue!

Testing on Wrath/Chinese is a bit extra work for me; I have an extra private server, but priority right now is the main version, and dont introduce bugs. 
Some frames are one line of code to activate the changes, but others require more work.

I will see what I can do. But for example the Talentframe is probably a good while away, because I made the Cata Talentframe for Era/SoD, it works great, but Wrath has glyphs, which require a chunk of extra work.

I will activate the frames without extra work for the next update, and then I'll see whats left to do.

**Comment by Karl-HeinzSchneider** [comment]
I did some testing and debugging on my private server:
1) Character frame works now
2) FriendsListFrame should have worked already, at least it does on my client
3) SpellbookFrame and the extra professions are opt-in via the DF options
4) Talentframe is not realistic right now. It should more or less work, but on my server I get errors because of 'PREVIEW_TALENT_PRIMARY_TREE_CHANGED' event not exisiting, but that seems to be a private server problem. And also I didnt implement the glyphs tab at all. I have an idea for glyphs, but it would be more or less blindly coding it.
5) Profession frame should work now, also opt-in. Cant really test here as my server isnt really set up for game mechanics
6) TrainerFrame should have worked already, at least on my end.

**Comment by Karl-HeinzSchneider** [comment]
v0.16++ will have the changes btw
