### ISSUE TITLE
Message: ...nterface\AddOns\DragonflightUI\Modules\Unitframe.lua:1587: attempt to call global 'UnitHasVehiclePlayerFrameUI' 

### ISSUE THREAD

**Issue by luttman** [Karl-HeinzSchneider/WoW-DragonflightUI#25]
Message: ...nterface\AddOns\DragonflightUI\Modules\Unitframe.lua:1587: attempt to call global 'UnitHasVehiclePlayerFrameUI' (a nil value)
Time: Sat May  6 12:39:17 2023
Count: 1
Stack: ...nterface\AddOns\DragonflightUI\Modules\Unitframe.lua:1587: attempt to call global 'UnitHasVehiclePlayerFrameUI' (a nil value)
[string "=[C]"]: in function `UnitHasVehiclePlayerFrameUI'
[string "@Interface\AddOns\DragonflightUI\Modules\Unitframe.lua"]:1587: in function <...nterface\AddOns\DragonflightUI\Modules\Unitframe.lua:1579>
[string "=[C]"]: in function `PlayerFrame_UpdateStatus'
[string "@Interface\FrameXML\PlayerFrame.lua"]:160: in function <Interface\FrameXML\PlayerFrame.lua:134>

Locals: 

After last update

**Comment by Karl-HeinzSchneider** [comment]
Weird. When does the error pop up, on login? 
Original blizzard code calls this function on the Playerframe, so it's kind of unexpected. 
And can you try `/dump UnitHasVehiclePlayerFrameUI('player')` ?
Should print like this: 
![image](https://user-images.githubusercontent.com/56960197/236645535-a56f9a97-82a9-44d3-9ab4-5552de88e1f1.png)
(first call was inside quest vehicle)


If its anoying, you can just change the code like this:
Modules/Unitframe.lua Line 1587:
`if (UnitHasVehiclePlayerFrameUI('player')) then` to  `if false then`

**Comment by luttman** [comment]
[image: image.png]
Classic Era

Den lör 6 maj 2023 kl 22:37 skrev Karl-HeinzSchneider <
***@***.***>:

**Comment by beadss** [comment]
Happens to me too

**Comment by Karl-HeinzSchneider** [comment]
Ahh, sure! On Era. Will update later with a fix; for now you can just change the code like i said in my last post. Thanks for reporting!

**Comment by Karl-HeinzSchneider** [comment]
Update for Era should be online soon! 
Had multiple issues with the new rest icon animation because other than the missing VehicleUI function the flipbook animations aren't supported on Era.

To Update get [DragonflightUI-v0.2.1.zip](https://legacy.curseforge.com/wow/addons/dragonflight-ui-classic/files/4529325) on Curse. (Wrath doesn't need update, but also works with the same files)

Thanks for reporting! Please feel free to suggest any feature you might like, or report any additional error you find.
