### ISSUE TITLE
[BUG] UI elements missing after version 1.15.4.56738

### ISSUE THREAD

**Issue by chsko** [Karl-HeinzSchneider/WoW-DragonflightUI#262]
**Describe the bug**
UI elements are missing, and the mail icon is displaced. 

Steps to reproduce:
1. Upgrade det wow client to the current latest version: 1.15.4.56738
2. Install the current latest version of Dragonflight-UI: 0.17
3. Start the game and log in to a character
4. Observe that UI elements are missing

Screenshot:
![dragonflight-ui-issues](https://github.com/user-attachments/assets/5bf386e5-d8da-49c7-b11d-f9e1941ce534)

**Error Log**
No Lua errors are observed

**Versions (please complete the following information):**
 - WoW: 1.15.4.56738
 - Addon 0.17

**Additional context**
All other addons have been disabled

**Comment by Karl-HeinzSchneider** [comment]
Yes, Actionbars need to be activated through the blizzard options; I can't through code, or I introduce taint and errors.
Somehow blizzard decided to reset those options on the latest update.

They changed a lot of code; I fixed the Mail position. Also got rid of some error inside the profession window, but still need some work there because the dropdown code changed (filter etc).
