### ISSUE TITLE
Bug: ActionBars not hiding grid

### ISSUE THREAD

**Issue by Splitix** [Karl-HeinzSchneider/WoW-DragonflightUI#58]
With the newest update, When turning off `Always show Actionbar` It works for the first one but when I go to do it for the next bar it resets the previous bar back to showing the grid on my screen. The button is still unchecked on that previous bar as well

/reload doesn't seem to fix the issue either.

**Comment by Karl-HeinzSchneider** [comment]
Yeah overriding the `Always show Actionbar` option is tricky, because in classic its all global. 
Is the grid fixed when you hover over the individual buttons with your mouse? Then they get updated from the blizzard code. 

I found a bug when the global option is not set, i think blizzard overrides my options then sometimes.
Can you try setting `Always show Actionbar` in the global blizzard options, and then just use the DragonflightUI settings to controll the individual bars? Seems to work fine for me after a possible reload.

**Comment by Splitix** [comment]
> Is the grid fixed when you hover over the individual buttons with your mouse? Then they get updated from the blizzard code.
Yeah that's how I was fixing it but was kind of annoying. 

> Can you try setting Always show Actionbar in the global blizzard options, and then just use the DragonflightUI settings to controll the individual bars?
Yeah that seems to work. I'll keep it this way. Thanks
