### ISSUE TITLE
0.5.0 'ghost' action bars

### ISSUE THREAD

**Issue by zedle** [Karl-HeinzSchneider/WoW-DragonflightUI#59]
I ended up downgrading to the previous version for now, but when I updated I had multiple of the same action bar. It looked like the normal blizzard position ones were rendering alongside the DragonflightUI ones, but the ghost ones were not interactable. Tried every setting I could think of both in the game settings and the addon settings to no avail.

Working for now on the old version but would like to update when this gets fixed. Surprised I'm not seeing others say anything, so maybe it's just me.

**Comment by Cortes-Jeremy** [comment]
Hey, got same problem, ended up desactivating another addon called tulla range for now.

**Comment by Karl-HeinzSchneider** [comment]
I'm away till friday, will take a look at it then. Can you post a list of your addons? I guess some addon changes something from the default bars (like DFui classic does)

**Comment by Karl-HeinzSchneider** [comment]
> Hey, got same problem, ended up desactivating another addon called tulla range for now.

Is it fixed for you then? Can take a look at the other addon on the weekend.

**Comment by Cortes-Jeremy** [comment]
Yeah its fixed if I remove this addon, joining you whats actually happening when this addon is enabled:
![Clipboard01](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/56119078/7bcbde87-7bc4-4a6e-b6ec-3194c1d03551)
If I try to find whats the frame with /fstack it give nothing.
Hope it can help.

**Comment by Tasten4** [comment]
Just wanted to check in on this since I'm also having this issue and it's been about a month since it was reported. Tulla Range is what's causing the issue with this mod. Basically if you remove the mod, it removes the duplicated action bar. The issue is Tulla Range seems to be the only addon right now that I can find that gives an easy to see "out of range" notificaiton aside from the default coloring of the number in the upper right corner of the button.

**Comment by Karl-HeinzSchneider** [comment]
Btw, v0.9 is live soon and has something like TullaRange, check it out!
