### ISSUE TITLE
Suggestion: personal resources and more hp mana numbers

### ISSUE THREAD

**Issue by Megumin230** [Karl-HeinzSchneider/WoW-DragonflightUI#69]
I really love this ui for classic and I think these are the only things missing from the ui to make it perfect, sorry in advance as these are only suggestions and I dont have the knowledge to contribute to making this, ty and I'd love to hear what you think

The more simple part is more options for hp and mana text, with the current settings I almost never look at the numbers bc im more used to seeing the number and letter or else my brain doesn't brain 99K or 99,9K for my character and for bosses 99,99M etc

This is current
![Screenshot 2024-04-25 112714](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/70694639/f2c4c331-77d8-4fe4-a04f-dda740fe133a)

This is what it looks in retail rn, so more options would make things easier on the eyes
![Screenshot 2024-04-25 105540](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/70694639/48c8d00d-0243-4c09-a85d-f7c625f932b4) 

An option to display all at the same time is also great with % either inside or outside
![Screenshot 2024-04-25 113055](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/70694639/8cc85c2e-fc62-4feb-bd33-0a377eb278fd)

And if it even possible to do, add personal resources: HP, Mana and class resources like holy power, along with absorb indicators and predictions for hp and mana

The personal resources
![Screenshot 2024-04-25 110846](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/70694639/1348c33e-11e6-4da0-92d4-5ffb7a253491) 

Absorb indicators
![Screenshot 2024-04-25 112150](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/70694639/99e5380f-16bf-4265-a793-18a5ba0f532f) 
![Screenshot 2024-04-25 112206](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/70694639/a567f8c2-ffd5-4597-8c04-1d9beca5c399)

Predictions for mana and hp increasing or decreasing with casts and received heals
![Screenshot 2024-04-25 111828](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/70694639/b2e0c6f4-3b15-4cab-a5b0-462fe0a638cf)

Thanks for reading!

**Comment by Karl-HeinzSchneider** [comment]
1) Currently I'm using the default Health/ManabarText, just moved etc. It's possible to change the number display logic, but involves a bit of work to get all edge cases. But I think that would be low priority.
The percent thing from your 3rd picture would be easy to do with WeakAuras.

2) The personal HP/Energy bars are nice, but would be a lot of work for every class with so different ressources. Personally I use a WeakAura to display HP/Mana/Holypower.
I would like to have something like the retail default bars, because I also dont like to setup WA's for every character/class; but it's low priority for now.

**Comment by journeym** [comment]
I missed the point, are predictions/absorbs implemented or not? If not, then is there any addon that works with these frames to get prediction working?
