### ISSUE TITLE
Stutter every 1sec

### ISSUE THREAD

**Issue by LouiXL** [Karl-HeinzSchneider/WoW-DragonflightUI#94]
I tested it with all addons disabled and just this addon, I get every 1 sec a minimal stutter that is super annoying. Love the DF UI and would love to use the addon on my cata journey, but I think I have to disable it for now :(

**Comment by Karl-HeinzSchneider** [comment]
Hey,
that doesnt seem right!
You could try to deactivate all modules, and then check one after another which one may cause stutter. If I know some place to start, I could try to investigate, but with a blank statement I cant, because I dont know your PC, other addons, settings, maybe some windows bug (for example, a friend has hard framedrops 250fps -> <60fps every 2-3s when using two monitors with different hz)

**Comment by LouiXL** [comment]
Completly understand your point, I just moved on cause it was too annoying. It only happened when I had your addon turned on so it must have to do something with it and not other addons / settings / windows "bugs" or w/e.

Thank you anyway I will revisit it in the future.
